---
- include: apt.yaml
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: make tmux plugins root repository
  file:
    path: "{{ tmux_plugins_root }}"
    state: directory
- name: git clone tpm
  git:
    depth: "{{ tpm_repository.depth }}"
    dest: "{{ tmux_plugins_root }}/tpm"
    repo: "{{ tpm_repository.url }}"

- name: install tmux plugins via tpm
  shell: "{{ tmux_plugins_root }}/tpm/bin/install_plugins"
