---
- name: apt install tmux
  become: yes
  apt:
    name:
      - tmux
    state: latest
- name: mkdir ~/.tmux/plugins
  file:
    path: "{{ dirs.tmux_plugins }}"
    state: directory
- name: git clone tpm
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ dirs.tpm }}"
    depth: 1
- name: create symlink of tmux.conf
  file:
    src: "{{ dirs.config.src }}"
    dest: "{{ dirs.config.dest }}"
    state: link
