- name: apt update/upgrade
  become: yes
  apt:
    update_cache: yes
    upgrade: safe
- name: apt install common packages
  become: yes
  apt:
    name: "{{ apt.packages }}"
    state: latest

- name: generate ssh key pair
  shell: |
    ssh-keygen -q -t ed25519 -N "" -C "vagrant@${HOST}" -f ~/.ssh/id_ed25519
    curl --user "epaew" -H "Accept: application/vnd.github.v3+json" \
      -X POST -d "{\"title\":\"$(uname -nr)\", \"key\":\"$(cat ~/.ssh/id_ed25519.pub)\"}" \
      https://api.github.com/user/keys
  args:
    creates: ~/.ssh/id_ed25519
    stdin: "{{ secrets.github }}"
- name: ensure github.com is a known host
  known_hosts:
    name: "{{ item }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -H ' + item) }}"
    hash_host: yes
  with_items:
    - "{{ global.domains.values() }}"

- name: clone epaew/dotfiles.git
  git:
    repo: https://github.com/epaew/dotfiles.git
    dest: "{{ global.dirs.dotfiles }}"
- name: create symlink of each dotfiles
  file:
    src: "{{ global.dirs.dotfiles }}/{{ item }}"
    dest: "{{ global.dirs.home }}/{{ item }}"
    state: link
  with_items: "{{ dotfiles.links }}"
- name: create copy of each dotfiles
  copy:
    src: "{{ global.dirs.dotfiles }}/{{ item }}"
    dest: "{{ global.dirs.home }}/{{ item }}"
    remote_src: yes
  with_items: "{{ dotfiles.copies }}"

- name: set bell style none
  copy:
    dest: ~/.inputrc
    content: "set bell-style none"
