---
rbenv:
  dirs:
    dest: ~/.rbenv
  repo:
    depth: 1
    url: https://github.com/rbenv/rbenv.git
  ruby_version: 2.7.1

  plugins:
    - name: ruby-build
      repo:
        depth: 1
        url: https://github.com/rbenv/ruby-build.git
