---
default_ruby_version: ''
extra_ruby_versions: []

rbenv_root: "{{ ansible_env.HOME }}/.rbenv"
rbenv_reposiory:
  depth: 1
  url: https://github.com/rbenv/rbenv.git
rbenv_plugins: []

ruby_build_repository:
  depth: 1
  url: https://github.com/rbenv/ruby-build.git
