---
- name: clone epaew/dotfiles.git
  git:
    depth: "{{ dotfiles.repo.depth }}"
    dest: "{{ dotfiles.dirs.dest }}"
    repo: "{{ dotfiles.repo.url }}"
- name: create copy of each dotfiles
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
  with_items: "{{ dotfiles.copy_files }}"
- name: create symlink of each dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items: "{{ dotfiles.link_files }}"
