---
- name: clone epaew/dotfiles.git
  git:
    depth: "{{ dotfiles_repository.depth }}"
    dest: "{{ dotfiles_root }}"
    repo: "{{ dotfiles_repository.url }}"
    version: "{{ dotfiles_repository.branch }}"
- name: create symlink of each dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items: "{{ dotfiles_to_link }}"
