---
- name: set bell style none
  copy:
    dest: ~/.inputrc
    content: |
      set bell-style none

- name: apt install common packages
  become: yes
  apt:
    name: "{{ common.apt.packages }}"
    state: latest

- name: set global git config
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - "{{ common.git.config }}"
