---
- name: set bell style none
  copy:
    dest: ~/.inputrc
    content: |
      set bell-style none

- name: mkdir $XDG_CONFIG_HOME
  file:
    path: "{{ xdg_config_home }}"
    state: directory

- name: apt install extra packages
  become: yes
  apt:
    name: "{{ extra_apt_packages }}"
    state: latest

- name: set global git config
  template:
    src: home/gitconfig.j2
    dest: "{{ ansible_env.HOME }}/.gitconfig"
