---
- include: apt.yaml
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: git clone zsh-completions
  git:
    depth: "{{ zsh.zsh_completions.repo.depth }}"
    dest: "{{ zsh.zsh_completions.dirs.dest }}"
    repo: "{{ zsh.zsh_completions.repo.url }}"

- name: set zsh as login shell
  become: yes
  shell: "chsh -s $(which zsh) {{ ansible_user_id }}"
