---
- include: apt.yaml
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: git clone zsh-completions
  git:
    depth: "{{ zsh_completions_repository.depth }}"
    dest: "{{ zsh_completions_checkout_path }}"
    repo: "{{ zsh_completions_repository.url }}"

- name: set zsh as login shell
  become: yes
  shell: "chsh -s $(which zsh) {{ ansible_user_id }}"
