---
nodenv:
  dirs:
    dest: ~/.nodenv
  repo:
    depth: 1
    url: https://github.com/nodenv/nodenv.git
  node_version: 12.16.3

  plugins:
    - name: node-build
      repo:
        depth: 1
        url: https://github.com/nodenv/node-build.git
