---
nodenv:
  dirs:
    nodenv:
      dest:  "~/.nodenv"
      plugins: "~/.nodenv/plugins"
    node_build: "~/.nodenv/plugins/node-build"
  node_version: "12.16.2"
  npm:
    packages:
      - name: yarn
