---
default_node_version: ''
extra_node_versions: []

nodenv_root: "{{ ansible_env.HOME }}/.nodenv"
nodenv_reposiory:
  depth: 1
  url: https://github.com/nodenv/nodenv.git
nodenv_plugins: []

node_build_repository:
  depth: 1
  url: https://github.com/nodenv/node-build.git
