- name: git clone nodenv
  git:
    dest: "{{ nodenv.dirs.dest }}"
    depth: "{{ nodenv.repo.depth }}"
    repo: "{{ nodenv.repo.url }}"
- name: compile nodenv
  shell: src/configure && make -C src
  args:
    chdir: "{{ nodenv.dirs.dest }}"
- name: mkdir ~/.nodenv/plugins
  file:
    path: "{{ nodenv.dirs.dest }}/plugins"
    state: directory
- name: git clone node-build
  git:
    dest: "{{ nodenv.dirs.dest }}/plugins/node-build"
    depth: "{{ node_build.repo.depth }}"
    repo: "{{ node_build.repo.url }}"
- name: nodenv install
  shell: |
    PATH="$HOME/.nodenv/bin:$PATH"
    eval "$(nodenv init -)"
    nodenv install {{ nodenv.node_version }}
    nodenv global {{ nodenv.node_version }}
  args:
    creates: "{{ nodenv.dirs.dest }}/versions/{{ nodenv.node_version }}"
  when: nodenv.node_version is defined
- name: install yarn
  npm:
    name: yarn
    global: yes
    state: latest
  environment:
    PATH: "{{ ansible_env.HOME }}/.nodenv/versions/{{ nodenv.node_version }}/bin:{{ ansible_env.PATH }}"
  when: nodenv.node_version is defined
