---
- name: mkdir for fzf
  file:
    path: "{{ fzf_root }}"
    state: directory
- name: clone git repository
  git:
    depth: "{{ fzf_repository.depth }}"
    dest: "{{ fzf_root }}"
    repo: "{{ fzf_repository.url }}"
    version: "{{ fzf_repository.branch }}"
- name: install fzf
  shell: "{{ fzf_root }}/install"
  args:
    creates: "{{ fzf_root }}/bin/fzf"
