---
tmux:
  dirs:
    plugins: ~/.tmux/plugins
  link_files:
    - src: ~/dotfiles/.tmux.conf
      dest: ~/.tmux.conf
  plugins:
    - name: tpm
      repo:
        depth: 1
        url: https://github.com/tmux-plugins/tpm.git
