---
rbenv:
  link_files:
    - src: ~/dotfiles/.gemrc
      dest: ~/.gemrc
    - src: ~/dotfiles/.pryrc
      dest: ~/.pryrc
    - src: ~/dotfiles/rbenv/default-gems
      dest: ~/.rbenv/default-gems
  ruby_version: 2.7.1
