---
- name: generate ssh key pair
  shell: |
    ssh-keygen -q -t ed25519 -N "" -C "${USER}@$(uname -nr)" -f ~/.ssh/id_ed25519
  args:
    creates: ~/.ssh/id_ed25519
- name: generate API body
  shell: |
    echo "{\"title\":\"$(uname -nr)\", \"key\":\"$(cat ~/.ssh/id_ed25519.pub)\"}"
  register: api_body

- name: register ssh public key to github.com
  uri:
    body: "{{ api_body.stdout }}"
    body_format: json
    headers:
      Accept: "application/vnd.github.v3+json"
      Authorization: "token {{ secrets.github_api_token }}"
    method: POST
    status_code: 201,422
    url: https://api.github.com/user/keys
- name: register ssh public key to gitlab.com
  uri:
    body: "{{ api_body.stdout }}"
    body_format: json
    headers:
      Private-Token: "{{ secrets.gitlab_api_token }}"
    method: POST
    status_code: 201,400
    url: https://gitlab.com/api/v4/user/keys

- name: ensure known hosts
  known_hosts:
    name: "{{ item }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -H ' + item) }}"
    hash_host: yes
  with_items:
    - "{{ known_hosts }}"
