---
- name: apt install zsh
  become: yes
  apt:
    name:
      - zsh
    state: latest
- name: create symlink of zshenv
  file:
    src: "{{ dirs.config.src }}"
    dest: "{{ dirs.config.dest }}"
    state: link
- name: git clone zsh-completions
  git:
    repo: https://github.com/zsh-users/zsh-completions.git
    dest: "{{ dirs.zsh_completions }}"
    depth: 1
- name: set zsh as login shell
  become: yes
  shell: "chsh -s '/usr/bin/zsh' {{ global.user.name }}"
