---
apt:
  packages:
    - apt-transport-https
    - ca-certificates
    - containerd.io
    - curl
    - docker-ce
    - docker-ce-cli
    - gnupg-agent
    - software-properties-common
  repos:
    - "deb https://download.docker.com/linux/ubuntu bionic stable"
