---
# This role does not work on WSL1
- include: "{{ ansible_distribution }}.yaml"

- debug:
    var: ansible_user_id
- name: add user to docker group
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- name: check current environment is WSL
  shell: uname -r | grep -iq microsoft
  register: is_wsl
  failed_when: false
- name: check systemctl is callable
  shell: type systemctl
  register: systemctl_present
  failed_when: false
- name: Enables docker daemon to start on boot (service)
  become: yes
  service:
    name: docker
    enabled: yes
    state: restarted
  when:
    - is_wsl.rc != "0"
    - systemctl_present != "0"
- name: Enables docker daemon to start on boot (systemd)
  become: yes
  systemd:
    name: docker
    enabled: yes
    state: restarted
  when:
    - is_wsl.rc != "0"
    - systemctl_present == "0"

- name: install docker-compose from pip3
  pip:
    name: docker-compose
    executable: /usr/bin/pip3 # Use pip3 installed via apt
    extra_args: --user
    state: latest
