---
- name: apt add docker repository key
  become: yes
  apt_key:
    url: "{{ docker.apt.repository_key_urls.ubuntu }}"
- name: apt add docker repository
  become: yes
  apt_repository:
    repo: |
      {{ docker.apt.repositories.ubuntu[ansible_distribution_major_version] }}
- name: apt install/update docker-ce
  become: yes
  apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
    state: latest
