---
- name: apt install ruby-build dependencies
  become: yes
  apt:
    name:
      - libreadline-dev
      - libssl-dev
      - zlib1g-dev
    state: latest
- name: git clone rbenv
  git:
    dest: "{{ rbenv.dirs.dest }}"
    depth: "{{ rbenv.repo.depth }}"
    repo: "{{ rbenv.repo.url }}"
- name: compile rbenv
  shell: src/configure && make -C src
  args:
    chdir: "{{ rbenv.dirs.dest }}"
- name: mkdir ~/.rbenv/plugins
  file:
    path: "{{ rbenv.dirs.dest }}/plugins"
    state: directory
- name: git clone rbenv plugins
  git:
    dest: "{{ rbenv.dirs.dest }}/plugins/{{ item.name }}"
    depth: "{{ item.repo.depth }}"
    repo: "{{ item.repo.url }}"
  with_items:
      - "{{ rbenv.plugins }}"

- name: rbenv install
  shell: |
    PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    rbenv install {{ rbenv.ruby_version }}
    rbenv global {{ rbenv.ruby_version }}
  args:
    creates: "{{ rbenv.dirs.dest }}/versions/{{ rbenv.ruby_version }}"
  when: rbenv.ruby_version is defined
