---
- name: apt install ruby-build dependencies
  become: yes
  apt:
    name:
      - libreadline-dev
      - libssl-dev
      - zlib1g-dev
    state: latest

- name: git clone rbenv
  git:
    dest: "{{ rbenv_root }}"
    depth: 1
    repo: "{{ rbenv_reposiory.url }}"
    version: "{{ rbenv_reposiory.branch }}"
- name: compile rbenv
  shell: src/configure && make -C src
  args:
    chdir: "{{ rbenv_root }}"
- name: mkdir ~/.rbenv/plugins
  file:
    path: "{{ rbenv_root }}/plugins"
    state: directory
- name: git clone rbenv plugins
  git:
    dest: "{{ rbenv_root }}/plugins/{{ item.name }}"
    depth: 1
    repo: "{{ item.repository.url }}"
    version: "{{ item.repository.branch }}"
  with_items:
    - "{{ rbenv_required_plugins }}"
    - "{{ rbenv_extra_plugins }}"
- name: replace ~/.rbenv/default-gems
  template:
    src: rbenv/default-gems.j2
    dest: "{{ rbenv_root }}/default-gems"

- name: rbenv install global
  shell: |
    eval "$(rbenv init -)"
    rbenv install {{ default_ruby_version }}
    rbenv global {{ default_ruby_version }}
  args:
    creates: "{{ rbenv_root }}/versions/{{ default_ruby_version }}"
  environment:
    PATH: "{{ rbenv_root }}/bin:{{ ansible_env.PATH }}"
  when:
    - default_ruby_version is defined
    - default_ruby_version|length > 0

- name: rbenv install extra
  shell: |
    eval "$(rbenv init -)"
    rbenv install {{ item }}
  args:
    creates: "{{ rbenv_root }}/versions/{{ item }}"
  environment:
    PATH: "{{ rbenv_root }}/bin:{{ ansible_env.PATH }}"
  with_items:
    - "{{ extra_ruby_versions }}"
