- name: apt install ruby-build dependencies
  become: yes
  apt:
    name:
      - git
      - libreadline-dev
      - libssl-dev
      - zlib1g-dev
    state: latest
- name: git clone rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: "{{ rbenv.dirs.rbenv.dest }}"
    depth: 1
- name: compile rbenv
  shell: src/configure && make -C src
  args:
    chdir: "{{ rbenv.dirs.rbenv.dest }}"
- name: mkdir ~/.rbenv/plugins
  file:
    path: "{{ rbenv.dirs.rbenv.plugins }}"
    state: directory
- name: git clone rbenv plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ rbenv.dirs.rbenv.plugins }}/{{ item.name }}"
    depth: 1
  with_items:
      - "{{ rbenv.plugins }}"
- name: create symlink of configs
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
      - "{{ rbenv.configs }}"
- name: rbenv install ruby
  shell: |
    PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    rbenv install {{ rbenv.ruby_version }}
    rbenv global {{ rbenv.ruby_version }}
  args:
    creates: "{{ rbenv.dirs.rbenv.dest }}/versions/{{ rbenv.ruby_version }}"
  when: rbenv.ruby_version is defined
