---
- name: apt install software-properties
  become: yes
  apt:
    name:
      - software-properties-common
      - python-software-properties
    state: latest
    update_cache: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version < "18"
- name: apt add neovim repository
  become: yes
  apt_repository:
    repo: ppa:neovim-ppa/stable
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version < "18"

- name: apt install neovim
  become: yes
  apt:
    name: neovim
    state: latest
    update_cache: yes
