---
- include: apt.yaml
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: pip3 install pynvim
  pip:
    name: pynvim
    executable: /usr/bin/pip3 # Use pip3 installed via apt
    extra_args: --user
    state: latest

- name: mkdir for dein
  file:
    path: "{{ dein.dirs.dest }}"
    state: directory
- name: git clone dein
  git:
    depth: "{{ dein.repo.depth }}"
    dest: "{{ dein.dirs.dest }}"
    repo: "{{ dein.repo.url }}"
