name: Test common role

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/test_common_role.yaml
      - roles/common/**
      - test/**
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 1 * *'

jobs:
  test-roles:
    name: Test common role
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linux:
          - distribution: ubuntu
            version: xenial
          - distribution: ubuntu
            version: bionic
          - distribution: ubuntu
            version: focal

    steps:
      - uses: actions/checkout@v2
      - name: Build docker image for test ansible role
        run: |
          docker build -f test/Dockerfiles/Dockerfile.${{ matrix.linux.distribution }} \
            --build-arg BASE_TAG=${{ matrix.linux.version }} \
            --build-arg ROLE_NAME=common \
            .
